Vagrant.configure(2) do |config|
  
  # if Vagrant.has_plugin?('vagrant-cachier')
  #   config.cache.enable :box
  # end
  
  config.vm.define "python-demo" do |server|
    server.vm.box = "rhel-server-7"

    #server.cache.enable :box
    server.cache.enable :yum
    
    server.vm.provision "shell", inline: "sudo subscription-manager repos --disable *-rt-* --disable *-eus* --disable *-rs-* --disable *-ha-*"
    server.vm.provision "shell", inline: "sudo subscription-manager repos --enable rhel-server-rhscl-7-rpms --enable rhel-7-server-optional-rpms"
    server.vm.provision "shell", inline: "sudo yum -y update"
    server.vm.provision "shell", inline: 'cat << EOF >> .bashrc
if [ "\$X_SCLS" ]; then
    PRETTY_SCLS=\${X_SCLS// /,}                                                                                                                      
    PRETTY_SCLS=\${PRETTY_SCLS/%,/}
    PS1="(\$PRETTY_SCLS) \$PS1"
fi
EOF'
    server.vm.provision "shell", inline: "sudo yum -y install rh-python34"

  end
end
