Vagrant.configure(2) do |config|
  #
  # Getting started on RedHat Enterprise Linux (RHEL) with vagrant
  #
  # To get started:
  # Download the cdk rhel-server vagrant box from https://access.redhat.com/downloads/content/293/ver=1/rhel---7/1.0.1/x86_64/product-software (you will need a Red Hat account)
  #
  # Add the box to vagrant
  # vagrant box add --name "rhel-server-7" rhel-server-libvirt-7.1-3.x86_64.box
  #
  # update to latest, this assumes you are using vagrant-registration to register: https://github.com/projectatomic/adb-vagrant-registration
  
  config.vm.define "python-demo" do |server|
    server.vm.box = "rhel-server-7"

    if Vagrant.has_plugin?('vagrant-cachier')
    	#server.cache.enable :box
    	server.cache.enable :yum
    end

    server.vm.provision "shell", inline: "sudo subscription-manager repos --disable *-rt-* --disable *-eus* --disable *-rs-* --disable *-ha-*"
    server.vm.provision "shell", inline: "sudo subscription-manager repos --enable rhel-server-rhscl-7-rpms --enable rhel-7-server-optional-rpms"
    server.vm.provision "shell", inline: "sudo yum -y update"
    server.vm.provision "shell", inline: 'cat << EOF >> .bashrc
if [ "\$X_SCLS" ]; then
    PRETTY_SCLS=\${X_SCLS// /,}                                                                                                                      
    PRETTY_SCLS=\${PRETTY_SCLS/%,/}
    PS1="(\$PRETTY_SCLS) \$PS1"
fi
EOF'
    server.vm.provision "shell", inline: "sudo yum -y install rh-python34"

  end
end
